/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.krasniqi.arian.ics3u.u3.unit6;

import edu.hdsb.gwss.krasniqi.arian.ics3u.u3.ArrayUtill.ArrayUtil;

/**
 *
 * @author ARIAN
 */
public class GolfGUI3 extends javax.swing.JFrame {

    /**
     * Creates new form GolfGUI3
     */
    public GolfGUI3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programTitleLabel = new javax.swing.JLabel();
        UserInfoLabel = new javax.swing.JLabel();
        scoreInputLabel = new javax.swing.JLabel();
        scoreInputText = new javax.swing.JTextField();
        scoreInputConfirmationButton = new javax.swing.JButton();
        displayGolfScoreButton = new javax.swing.JButton();
        holeAmountDisplay = new javax.swing.JLabel();
        scorePerHoleDisplay1 = new javax.swing.JLabel();
        scorePerHoleDisplay2 = new javax.swing.JLabel();
        scorePerHoleDisplay3 = new javax.swing.JLabel();
        minimumScoreDisplay = new javax.swing.JLabel();
        maximumScoreDisplay = new javax.swing.JLabel();
        totalScoreDisplay = new javax.swing.JLabel();
        scorePerHoleDisplay4 = new javax.swing.JLabel();
        scorePerHoleDisplay5 = new javax.swing.JLabel();
        scorePerHoleDisplay6 = new javax.swing.JLabel();
        scorePerHoleDisplay7 = new javax.swing.JLabel();
        scorePerHoleDisplay8 = new javax.swing.JLabel();
        scorePerHoleDisplay9 = new javax.swing.JLabel();
        scorePerHoleDisplay10 = new javax.swing.JLabel();
        scorePerHoleDisplay11 = new javax.swing.JLabel();
        scorePerHoleDisplay12 = new javax.swing.JLabel();
        scorePerHoleDisplay13 = new javax.swing.JLabel();
        scorePerHoleDisplay14 = new javax.swing.JLabel();
        scorePerHoleDisplay15 = new javax.swing.JLabel();
        scorePerHoleDisplay16 = new javax.swing.JLabel();
        scorePerHoleDisplay17 = new javax.swing.JLabel();
        scorePerHoleDisplay18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programTitleLabel.setText("Golf Score");

        UserInfoLabel.setText("This program records scores for an 18 hole golf course!");

        scoreInputLabel.setToolTipText("");
        scoreInputLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                scoreInputLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        scoreInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreInputTextActionPerformed(evt);
            }
        });

        scoreInputConfirmationButton.setText("Enter");
        scoreInputConfirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreInputConfirmationButtonActionPerformed(evt);
            }
        });

        displayGolfScoreButton.setText("Press To Display Results");
        displayGolfScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGolfScoreButtonActionPerformed(evt);
            }
        });

        holeAmountDisplay.setToolTipText("");

        scorePerHoleDisplay1.setToolTipText("");

        scorePerHoleDisplay2.setToolTipText("");

        minimumScoreDisplay.setToolTipText("");

        totalScoreDisplay.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(programTitleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scoreInputLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserInfoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(scoreInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scoreInputConfirmationButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(holeAmountDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(displayGolfScoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                    .addComponent(minimumScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maximumScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scorePerHoleDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scorePerHoleDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scorePerHoleDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scorePerHoleDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scorePerHoleDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scorePerHoleDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scorePerHoleDisplay8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scorePerHoleDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scorePerHoleDisplay9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scorePerHoleDisplay10, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scorePerHoleDisplay18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(programTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreInputConfirmationButton))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayGolfScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scorePerHoleDisplay10))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay2)
                            .addComponent(scorePerHoleDisplay11))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay3)
                            .addComponent(scorePerHoleDisplay12))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay4)
                            .addComponent(scorePerHoleDisplay13))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay5)
                            .addComponent(scorePerHoleDisplay14))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay6)
                            .addComponent(scorePerHoleDisplay15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(holeAmountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimumScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximumScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(totalScoreDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay7)
                            .addComponent(scorePerHoleDisplay16))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scorePerHoleDisplay8)
                            .addComponent(scorePerHoleDisplay17))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scorePerHoleDisplay9)
                    .addComponent(scorePerHoleDisplay18))
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreInputLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_scoreInputLabelAncestorAdded
        // TODO add your handling code here:

        scoreInputLabel.setText("Please enter your score for hole: " + (counter + 1));

        counter++;
    }//GEN-LAST:event_scoreInputLabelAncestorAdded

    private void scoreInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreInputTextActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_scoreInputTextActionPerformed

    private void scoreInputConfirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreInputConfirmationButtonActionPerformed
        // TODO add your handling code here:

        score[counter] = Integer.parseInt(scoreInputText.getText());

        scoreInputLabel.setText("Please enter your score for hole: " + (counter + 1));
        counter++;

        if (counter > numberOfHoles) {
            scoreInputText.setEditable(false);

        }
    }//GEN-LAST:event_scoreInputConfirmationButtonActionPerformed

    private void displayGolfScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayGolfScoreButtonActionPerformed
        // TODO add your handling code here:
        holeAmountDisplay.setText("Holes Played : " + numberOfHoles);

        int count = 0;

        scorePerHoleDisplay1.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;

        scorePerHoleDisplay2.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;

        scorePerHoleDisplay3.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;

        scorePerHoleDisplay4.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay5.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay6.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay7.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay8.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay9.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay10.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay11.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay12.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay13.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay14.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay15.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay16.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay17.setText("Hole : " + (count + 1) + " = " + score[count]);

        count++;
        scorePerHoleDisplay18.setText("Hole : " + (count + 1) + " = " + score[count]);

        int min = ArrayUtil.calculatingMinimum(score);
        minimumScoreDisplay.setText("Your Minimum Score was: " + min);

        int max = ArrayUtil.calculatingMaximum(score);
        maximumScoreDisplay.setText("Your Maximum score was: " + max);

        int total = ArrayUtil.calculatingSum(score);
        totalScoreDisplay.setText("Your Total score was: " + total);


    }//GEN-LAST:event_displayGolfScoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GolfGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GolfGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GolfGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GolfGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GolfGUI3().setVisible(true);
            }
        });
    }
    static int counter = 0;
    static int numberOfHoles = 18;
    static int[] score = new int[18];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserInfoLabel;
    private javax.swing.JButton displayGolfScoreButton;
    private javax.swing.JLabel holeAmountDisplay;
    private javax.swing.JLabel maximumScoreDisplay;
    private javax.swing.JLabel minimumScoreDisplay;
    private javax.swing.JLabel programTitleLabel;
    private javax.swing.JButton scoreInputConfirmationButton;
    private javax.swing.JLabel scoreInputLabel;
    private javax.swing.JTextField scoreInputText;
    private javax.swing.JLabel scorePerHoleDisplay1;
    private javax.swing.JLabel scorePerHoleDisplay10;
    private javax.swing.JLabel scorePerHoleDisplay11;
    private javax.swing.JLabel scorePerHoleDisplay12;
    private javax.swing.JLabel scorePerHoleDisplay13;
    private javax.swing.JLabel scorePerHoleDisplay14;
    private javax.swing.JLabel scorePerHoleDisplay15;
    private javax.swing.JLabel scorePerHoleDisplay16;
    private javax.swing.JLabel scorePerHoleDisplay17;
    private javax.swing.JLabel scorePerHoleDisplay18;
    private javax.swing.JLabel scorePerHoleDisplay2;
    private javax.swing.JLabel scorePerHoleDisplay3;
    private javax.swing.JLabel scorePerHoleDisplay4;
    private javax.swing.JLabel scorePerHoleDisplay5;
    private javax.swing.JLabel scorePerHoleDisplay6;
    private javax.swing.JLabel scorePerHoleDisplay7;
    private javax.swing.JLabel scorePerHoleDisplay8;
    private javax.swing.JLabel scorePerHoleDisplay9;
    private javax.swing.JLabel totalScoreDisplay;
    // End of variables declaration//GEN-END:variables
}
