/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.krasniqi.arian.ics3u.u3.unit6;

import edu.hdsb.gwss.krasniqi.arian.ics3u.u3.ArrayUtill.ArrayUtil;
import java.text.NumberFormat;

/**
 *
 * @author ARIAN
 */
public class TableSortGUI extends javax.swing.JFrame {

    /**
     * Creates new form TableSortGUI
     */
    public TableSortGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        CentralTeamLAbel = new javax.swing.JLabel();
        AmountOfWinsLabel = new javax.swing.JLabel();
        AmountOfLossesLabel = new javax.swing.JLabel();
        WinPercentageLabel = new javax.swing.JLabel();
        GamesBehindLabel = new javax.swing.JLabel();
        WinLossStreakLabel = new javax.swing.JLabel();
        ThirdTeamLabel = new javax.swing.JLabel();
        SecondTeamLabel = new javax.swing.JLabel();
        FirstTeamLabel = new javax.swing.JLabel();
        FourthTeamLabel = new javax.swing.JLabel();
        FifthTeamLabel = new javax.swing.JLabel();
        ThirdWinLabel = new javax.swing.JLabel();
        ThirdLossLabel = new javax.swing.JLabel();
        ThirdWinPercentageLabel = new javax.swing.JLabel();
        ThirdGamesBehindLabel = new javax.swing.JLabel();
        ThirdWinLossStreakLabel = new javax.swing.JLabel();
        SecondWinLabel = new javax.swing.JLabel();
        SecondLossLabel = new javax.swing.JLabel();
        SecondWinPercentageLabel = new javax.swing.JLabel();
        SecondGamesBehindLabel = new javax.swing.JLabel();
        SecondWinLossStreakLabel = new javax.swing.JLabel();
        FirstWinLabel = new javax.swing.JLabel();
        FirstLossLabel = new javax.swing.JLabel();
        FirstWinPercentageLabel = new javax.swing.JLabel();
        FirstGamesBehindLabel = new javax.swing.JLabel();
        FirstWinLossStreakLabel = new javax.swing.JLabel();
        FourthWinLabel = new javax.swing.JLabel();
        FourthLossLabel = new javax.swing.JLabel();
        FourthWinPercentageLabel = new javax.swing.JLabel();
        FourthGameBehindLabel = new javax.swing.JLabel();
        FourthWinLossStreak = new javax.swing.JLabel();
        FifthWinLabel = new javax.swing.JLabel();
        FifthLossLabel = new javax.swing.JLabel();
        FifthWinPercentageLabel = new javax.swing.JLabel();
        FifthGameBehindLabel = new javax.swing.JLabel();
        FifthWinLossStreakLabel = new javax.swing.JLabel();
        WinAscendingSortButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setText("Central NBA Standings Season 2014 / 2015");

        CentralTeamLAbel.setText("Central");

        AmountOfWinsLabel.setText("Wins");

        AmountOfLossesLabel.setText("Loss");

        WinPercentageLabel.setText("Win Percentage");

        GamesBehindLabel.setText("Games Behind");

        WinLossStreakLabel.setText("Win/Loss Streak");

        ThirdTeamLabel.setText("Cavaliers");

        SecondTeamLabel.setText("Bulls");

        FirstTeamLabel.setText("Bucks");

        FourthTeamLabel.setText("Pacers");

        FifthTeamLabel.setText("Pistons");

        ThirdWinLabel.setText("53");

        ThirdLossLabel.setText("29");

        ThirdWinPercentageLabel.setText(".646");

        ThirdGamesBehindLabel.setText("0.0");

        ThirdWinLossStreakLabel.setText("W2");

        SecondWinLabel.setText("50");

        SecondLossLabel.setText("32");

        SecondWinPercentageLabel.setText(".610");

        SecondGamesBehindLabel.setText("3.0");

        SecondWinLossStreakLabel.setText("W4");

        FirstWinLabel.setText("41");

        FirstLossLabel.setText("41");

        FirstWinPercentageLabel.setText(".500");

        FirstGamesBehindLabel.setText("12.0");

        FirstWinLossStreakLabel.setText("L1");

        FourthWinLabel.setText("38");

        FourthLossLabel.setText("44");

        FourthWinPercentageLabel.setText(".463");

        FourthGameBehindLabel.setText("15.0");

        FourthWinLossStreak.setText("L1");

        FifthWinLabel.setText("32");

        FifthLossLabel.setText("50");

        FifthWinPercentageLabel.setText(".390");

        FifthGameBehindLabel.setText("21.0");

        FifthWinLossStreakLabel.setText("W1");

        WinAscendingSortButton.setText("Wins (Ascending )");
        WinAscendingSortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WinAscendingSortButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(TitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecondTeamLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CentralTeamLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WinAscendingSortButton)
                                    .addComponent(FifthTeamLabel)
                                    .addComponent(FirstTeamLabel)
                                    .addComponent(ThirdTeamLabel)
                                    .addComponent(FourthTeamLabel))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AmountOfWinsLabel)
                                    .addComponent(SecondWinLabel)
                                    .addComponent(FourthWinLabel)
                                    .addComponent(FifthWinLabel)
                                    .addComponent(FirstWinLabel)
                                    .addComponent(ThirdWinLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AmountOfLossesLabel)
                                    .addComponent(SecondLossLabel)
                                    .addComponent(FourthLossLabel)
                                    .addComponent(FifthLossLabel)
                                    .addComponent(FirstLossLabel)
                                    .addComponent(ThirdLossLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WinPercentageLabel)
                                    .addComponent(SecondWinPercentageLabel)
                                    .addComponent(FourthWinPercentageLabel)
                                    .addComponent(FifthWinPercentageLabel)
                                    .addComponent(FirstWinPercentageLabel)
                                    .addComponent(ThirdWinPercentageLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GamesBehindLabel)
                                    .addComponent(SecondGamesBehindLabel)
                                    .addComponent(FourthGameBehindLabel)
                                    .addComponent(FifthGameBehindLabel)
                                    .addComponent(FirstGamesBehindLabel)
                                    .addComponent(ThirdGamesBehindLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ThirdWinLossStreakLabel)
                                    .addComponent(FirstWinLossStreakLabel)
                                    .addComponent(SecondWinLossStreakLabel)
                                    .addComponent(WinLossStreakLabel)
                                    .addComponent(FifthWinLossStreakLabel)
                                    .addComponent(FourthWinLossStreak))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(WinAscendingSortButton)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CentralTeamLAbel)
                    .addComponent(AmountOfWinsLabel)
                    .addComponent(AmountOfLossesLabel)
                    .addComponent(WinPercentageLabel)
                    .addComponent(GamesBehindLabel)
                    .addComponent(WinLossStreakLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstTeamLabel)
                    .addComponent(FirstWinLabel)
                    .addComponent(FirstLossLabel)
                    .addComponent(FirstWinPercentageLabel)
                    .addComponent(FirstGamesBehindLabel)
                    .addComponent(FirstWinLossStreakLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondTeamLabel)
                    .addComponent(SecondWinLabel)
                    .addComponent(SecondLossLabel)
                    .addComponent(SecondWinPercentageLabel)
                    .addComponent(SecondGamesBehindLabel)
                    .addComponent(SecondWinLossStreakLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThirdTeamLabel)
                    .addComponent(ThirdWinLabel)
                    .addComponent(ThirdLossLabel)
                    .addComponent(ThirdWinPercentageLabel)
                    .addComponent(ThirdGamesBehindLabel)
                    .addComponent(ThirdWinLossStreakLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourthTeamLabel)
                    .addComponent(FourthWinLabel)
                    .addComponent(FourthLossLabel)
                    .addComponent(FourthWinPercentageLabel)
                    .addComponent(FourthGameBehindLabel)
                    .addComponent(FourthWinLossStreak))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FifthWinLossStreakLabel)
                    .addComponent(FifthGameBehindLabel)
                    .addComponent(FifthWinPercentageLabel)
                    .addComponent(FifthLossLabel)
                    .addComponent(FifthWinLabel)
                    .addComponent(FifthTeamLabel))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WinAscendingSortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WinAscendingSortButtonActionPerformed

        NumberFormat decimal = NumberFormat.getNumberInstance();
        decimal.setMinimumFractionDigits(3);
        decimal.setMaximumFractionDigits(3);

        ArrayUtil.selectionSort(wins);
        ArrayUtil.selectionSort(loss);
        ArrayUtil.selectionSortForDouble(winPCT);
        ArrayUtil.selectionSortForDouble(gamesBehind);

        FirstTeamLabel.setText(teams[4]);
        SecondTeamLabel.setText(teams[3]);
        ThirdTeamLabel.setText(teams[2]);
        FourthTeamLabel.setText(teams[1]);
        FifthTeamLabel.setText(teams[0]);
        FirstWinLabel.setText(Integer.toString(wins[0]));
        SecondWinLabel.setText(Integer.toString(wins[1]));
        ThirdWinLabel.setText(Integer.toString(wins[2]));
        FourthWinLabel.setText(Integer.toString(wins[3]));
        FifthWinLabel.setText(Integer.toString(wins[4]));

        FirstLossLabel.setText(Integer.toString(loss[0]));
        SecondLossLabel.setText(Integer.toString(loss[1]));
        ThirdLossLabel.setText(Integer.toString(loss[2]));
        FourthLossLabel.setText(Integer.toString(loss[3]));
        FifthLossLabel.setText(Integer.toString(loss[4]));

        FirstWinPercentageLabel.setText(decimal.format(Double.toString(winPCT[0])));
        SecondWinPercentageLabel.setText(decimal.format(Double.toString(winPCT[1])));
        ThirdWinPercentageLabel.setText(decimal.format(Double.toString(winPCT[2])));
        FourthWinPercentageLabel.setText(decimal.format(Double.toString(winPCT[3])));
        FifthWinPercentageLabel.setText(decimal.format(Double.toString(winPCT[4])));

        FirstGamesBehindLabel.setText(decimal.format(Double.toString(gamesBehind[4])));
        SecondGamesBehindLabel.setText(decimal.format(Double.toString(gamesBehind[3])));
        ThirdGamesBehindLabel.setText(decimal.format(Double.toString(gamesBehind[2])));
        FourthGameBehindLabel.setText(decimal.format(Double.toString(gamesBehind[1])));
        FifthGameBehindLabel.setText(decimal.format(Double.toString(gamesBehind[0])));
        
      


    }//GEN-LAST:event_WinAscendingSortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableSortGUI().setVisible(true);
            }
        });
    }

    static int[] wins = {53, 50, 41, 38, 32};
    static String[] teams = {" Cavaliers", "Bulls", "Bucks", "Pacers", "Pistons"};
    static int[] loss = {41, 29, 32, 44, 50};
    static double[] winPCT = {.500, .610, .646, .463, .390};
    static double[] gamesBehind = {12.0, 3.0, 0.0, 15.0, 21.0};
    static String[] winLossStreak = {"L1", "W4", "W2", "L1", "W1"};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountOfLossesLabel;
    private javax.swing.JLabel AmountOfWinsLabel;
    private javax.swing.JLabel CentralTeamLAbel;
    private javax.swing.JLabel FifthGameBehindLabel;
    private javax.swing.JLabel FifthLossLabel;
    private javax.swing.JLabel FifthTeamLabel;
    private javax.swing.JLabel FifthWinLabel;
    private javax.swing.JLabel FifthWinLossStreakLabel;
    private javax.swing.JLabel FifthWinPercentageLabel;
    private javax.swing.JLabel FirstGamesBehindLabel;
    private javax.swing.JLabel FirstLossLabel;
    private javax.swing.JLabel FirstTeamLabel;
    private javax.swing.JLabel FirstWinLabel;
    private javax.swing.JLabel FirstWinLossStreakLabel;
    private javax.swing.JLabel FirstWinPercentageLabel;
    private javax.swing.JLabel FourthGameBehindLabel;
    private javax.swing.JLabel FourthLossLabel;
    private javax.swing.JLabel FourthTeamLabel;
    private javax.swing.JLabel FourthWinLabel;
    private javax.swing.JLabel FourthWinLossStreak;
    private javax.swing.JLabel FourthWinPercentageLabel;
    private javax.swing.JLabel GamesBehindLabel;
    private javax.swing.JLabel SecondGamesBehindLabel;
    private javax.swing.JLabel SecondLossLabel;
    private javax.swing.JLabel SecondTeamLabel;
    private javax.swing.JLabel SecondWinLabel;
    private javax.swing.JLabel SecondWinLossStreakLabel;
    private javax.swing.JLabel SecondWinPercentageLabel;
    private javax.swing.JLabel ThirdGamesBehindLabel;
    private javax.swing.JLabel ThirdLossLabel;
    private javax.swing.JLabel ThirdTeamLabel;
    private javax.swing.JLabel ThirdWinLabel;
    private javax.swing.JLabel ThirdWinLossStreakLabel;
    private javax.swing.JLabel ThirdWinPercentageLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton WinAscendingSortButton;
    private javax.swing.JLabel WinLossStreakLabel;
    private javax.swing.JLabel WinPercentageLabel;
    // End of variables declaration//GEN-END:variables
}
