/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.krasniqi.arian.ics3u.u3.unit6;

import edu.hdsb.gwss.krasniqi.arian.ics3u.u3.ArrayUtill.ArrayUtil;
import java.text.NumberFormat;

/**
 *
 * @author ARIAN
 */
public class TemperatureGUI extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureGUI
     */
    public TemperatureGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programTitleLabel = new javax.swing.JLabel();
        programUserInfoLabel = new javax.swing.JLabel();
        weekDayInputTemperatureLabel = new javax.swing.JLabel();
        dailyHighTemperatureInput = new javax.swing.JTextField();
        dailyHighConfirmationButton = new javax.swing.JButton();
        displayTemperatureButton = new javax.swing.JButton();
        maximumTemperatureDisplay = new javax.swing.JLabel();
        minimumTemperatureDisplay = new javax.swing.JLabel();
        averageTemperatureDisplay = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay1 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay2 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay3 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay4 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay5 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay6 = new javax.swing.JLabel();
        dayOfWeekTemperatureDisplay7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programTitleLabel.setText("Daily Temperatures For A Week");

        programUserInfoLabel.setText("This program records the daily Maximum Temperatures for a week");

        weekDayInputTemperatureLabel.setText("question");
        weekDayInputTemperatureLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                weekDayInputTemperatureLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        dailyHighConfirmationButton.setText("Enter");
        dailyHighConfirmationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyHighConfirmationButtonActionPerformed(evt);
            }
        });

        displayTemperatureButton.setText("Display Temperatures");
        displayTemperatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTemperatureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(programUserInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(weekDayInputTemperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(displayTemperatureButton, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(maximumTemperatureDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(minimumTemperatureDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(averageTemperatureDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dailyHighTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(dailyHighConfirmationButton))
                            .addComponent(dayOfWeekTemperatureDisplay3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayOfWeekTemperatureDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(programTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programUserInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekDayInputTemperatureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyHighTemperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dailyHighConfirmationButton))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayTemperatureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayOfWeekTemperatureDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayOfWeekTemperatureDisplay2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maximumTemperatureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayOfWeekTemperatureDisplay3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumTemperatureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayOfWeekTemperatureDisplay4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dayOfWeekTemperatureDisplay5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(averageTemperatureDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayOfWeekTemperatureDisplay6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayOfWeekTemperatureDisplay7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weekDayInputTemperatureLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_weekDayInputTemperatureLabelAncestorAdded
        // TODO add your handling code here:

        weekDayInputTemperatureLabel.setText("Please enter the Daily High for: " + days[counter]);
    }//GEN-LAST:event_weekDayInputTemperatureLabelAncestorAdded

    private void dailyHighConfirmationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyHighConfirmationButtonActionPerformed
        // TODO add your handling code here:

        temperature[counter] = Integer.parseInt(dailyHighTemperatureInput.getText());

        weekDayInputTemperatureLabel.setText("Please enter the Daily High for: " + days[counter + 1]);
        counter++;

        if (counter > temperature.length) {
            dailyHighTemperatureInput.setEditable(false);

        }


    }//GEN-LAST:event_dailyHighConfirmationButtonActionPerformed

    private void displayTemperatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTemperatureButtonActionPerformed
        // TODO add your handling code here:
        NumberFormat decimal = NumberFormat.getNumberInstance();
        decimal.setMinimumFractionDigits(2);
        decimal.setMaximumFractionDigits(2);

        int min = ArrayUtil.calculatingMinimum(temperature);
        int max = ArrayUtil.calculatingMaximum(temperature);
        double average = ArrayUtil.calculatingAverage(temperature);

        minimumTemperatureDisplay.setText("The lowest Temperature this week was: " + min);

        maximumTemperatureDisplay.setText("The highest Temperature this week was: " + max);

        averageTemperatureDisplay.setText("The average Temperature this week was: " + decimal.format(average));

        int count = 0;
        dayOfWeekTemperatureDisplay1.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay2.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay3.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay4.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay5.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay6.setText(days[count] + ": " + temperature[count]);
        count++;
        dayOfWeekTemperatureDisplay7.setText(days[count] + ": " + temperature[count]);


    }//GEN-LAST:event_displayTemperatureButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureGUI().setVisible(true);
            }
        });
    }

    static int counter = 0;
    static String[] days
            = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",};
    static int[] temperature = new int[7];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageTemperatureDisplay;
    private javax.swing.JButton dailyHighConfirmationButton;
    private javax.swing.JTextField dailyHighTemperatureInput;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay1;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay2;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay3;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay4;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay5;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay6;
    private javax.swing.JLabel dayOfWeekTemperatureDisplay7;
    private javax.swing.JButton displayTemperatureButton;
    private javax.swing.JLabel maximumTemperatureDisplay;
    private javax.swing.JLabel minimumTemperatureDisplay;
    private javax.swing.JLabel programTitleLabel;
    private javax.swing.JLabel programUserInfoLabel;
    private javax.swing.JLabel weekDayInputTemperatureLabel;
    // End of variables declaration//GEN-END:variables
}
